### ISSUE TITLE
Naglios => Slack интеграция

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#10]
https://slack.com/apps/A0F81R747-nagios

**Comment by ignisf** [comment]
cc @zeridon

**Comment by zeridon** [comment]
Ще го разгледам и ще видим как ще направим интеграцията

**Comment by zeridon** [comment]
Интеграцията е пусната в slack само трябва да се пращат алертите на там

**Comment by lz1irq** [comment]
Имаме настроена и тествана интеграция.
