### ISSUE TITLE
Оптимизиране на мониторинга на wifi

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#11]

**Comment by ignisf** [comment]
@tochev, това можеш да го хванеш, ако искаш :). Шел скриптът граби една камара неща от sysfs, просто трябва да се пооптимизира чрез пренаписване на C. <3

Може да видиш iwinfo и ethtool по какъв начин достъпват данните.

**Comment by tochev** [comment]
Ще видя дали ще ми остане време в следващите два weekend-a, но не обещавам.

Нали става въпрос за https://github.com/OpenFest/openfest-network/blob/master/monitoring/collectd/scripts/wlstats-gather/wlstats-gather.sh ?

**Comment by ignisf** [comment]
да.
