### ISSUE TITLE
Мониторинг на up/down състояние на wifi интерфейсите на AP-тата

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#13]
https://htmlpreview.github.io/?https://raw.githubusercontent.com/openwrt/luci/master/documentation/api/modules/luci.sys.wifi.html#wifi.getiwinfo maybe?

https://htmlpreview.github.io/?https://raw.githubusercontent.com/openwrt/luci/master/documentation/api/modules/luci.sys.net.html#net.deviceinfo

**Comment by ignisf** [comment]
https://wiki.openwrt.org/doc/techref/ubus#access_to_ubus_over_http

**Comment by ignisf** [comment]
Ще инсталирам snmpd на машинките и трябва да се добавят в nagios

**Comment by zeridon** [comment]
Nagios има конфигурация за мониторинг на `ifOperStatus` на интерфейс по име. Текущо настроени мониторинг на `wlan0` и `wlan1`

**Comment by ignisf** [comment]
yep, done
