### ISSUE TITLE
Конфигурация на нет от NETX

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#25]
Конфигурация от netx - 2 седмици по рано

**Comment by ignisf** [comment]
Ще ги питам, когато отидем да гледаме https://github.com/OpenFest/openfest-network/issues/61

**Comment by zeridon** [comment]
@ignisf Имаме ли информация за ъплинк конфигурацията?

**Comment by ignisf** [comment]
В понеделник.

**Comment by krokodilerian** [comment]
ipv6 address NetX - 2a01:b760:1:2::1/120
ipv6 address peer - 2a01:b760:1:2::2/120

2a01:b760:0:8::/64 static route to 2a01:b760:1:2::2

185.108.141.104/30 v4

Дали са ни /64, говоря за повече в момента

**Comment by krokodilerian** [comment]
ipv6 route 2a01:b760:2:4::/62 2a01:b760:1:2::2

**Comment by krokodilerian** [comment]
Config-ът е налят на ерик.

**Comment by ignisf** [comment]
done
