### ISSUE TITLE
Nagios - update

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#27]
trap per port

**Comment by zeridon** [comment]
Свършено:
- Добавени са всички суичове
- Добавени са всички wifi-та
- Добавени са (почти всички портове)
- Надписани са зависимости (нагиос е педерас и чеква зависими хостове въпреки че parent хоста е долу)

**Comment by zeridon** [comment]
Отделен трап за всеки порт е възможен но твърде неудобно за конфигуриране и обработка. Ще е като миналата година с една обща аларма за трап-ове

**Comment by krokodilerian** [comment]
Генериране със скрипт?

**Comment by zeridon** [comment]
Не става. Отделни сървиси за всеки трап после пипане на ръка на мибове ... Или поне нямам желание да си троша главата с това

**Comment by ignisf** [comment]
Май не стигнахме до trap per port
