### ISSUE TITLE
graphite/collectd/grafana - update

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#28]
- [x] latest grafana
- [x] latest collectd
- [x] latest graphite (if sensible)
- [x] Повече мониторвани неща в колектд
- [ ] Дашборди където е необходимо

**Comment by ignisf** [comment]
Да се добави функционалност за ембедване в сайта.

**Comment by ignisf** [comment]
Тук остава да се разберем къде да се публикуват?

**Comment by zeridon** [comment]
#64 Покрива дашбордите
