### ISSUE TITLE
Конфигуриране на SWITCHES

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#30]
Конфигурация на суичовете по схема. Трябва на всеки да се конфигурират:
- логин парола
- enable парола
- SNMP пароли (v2c)
- Trunk портове до другите суичове
- VLAN където трябва
- STP (pvstp)

**NOCSW** е отделна риба. Той има портове от всички VLAN-и
- [x] coresw
- [x] vocsw
- [x] nocsw
- [x] wssw
- [x] mussw
- [x] receptionsw
- [x] camsw
- [x] f2sw
- [x] teamsw

**Comment by ignisf** [comment]
Почти всички суичове са в лаба, предстои да ги струпаме и разпределим по зали.

**Comment by zeridon** [comment]
Почти финализирана схема на мрежата има в #66

**Comment by zeridon** [comment]
@krokodilerian моля погледни https://github.com/OpenFest/openfest-network/blob/master/switch-configs/vocsw.cfg дали е коректен спрямо изискванията че ми е за сефте да го конфигвам

**Comment by krokodilerian** [comment]
порт 5 няма description и не е down, това трябва да е AP1?
може би timezone трябва да е +0300
няма default gw и няма да работи ntp-то (може би трябва да му дадем 10.100.0.1 за ntp сървър)
нямахме ли централизиран logging?

Това ми хрумва, утре на по-будно ще го погледна пак. Иначе, може като цяло да видим config-а от switch-а от Светла, там вероятно има някакви пропуснати подробности (миналата година беше coresw и там не е пипана конфигурацията)

**Comment by zeridon** [comment]
Catalyst Express 500G суича е безбожен за конфигуриране. Да може и да има "cli-ish" шит но аз не искам да го конфигурирам. Ако някой изявява желание да заповяда, аз пропускам.

Вместо него слагам 24-портови 3750G който още не е в лаба-а.

**Comment by krokodilerian** [comment]
Аз ще го вдигна, с него си играх преди известно време.

**Comment by zeridon** [comment]
Готвим го за wssw :P have fun.

**Comment by krokodilerian** [comment]
ОК, fuck this. Махнете го тоя switch, не мога да намеря как да сменя името на mst domain-а :)

**Comment by ignisf** [comment]
😂

**Comment by zeridon** [comment]
Всички суичове са наконфени. Почистени конфизи са качени в репото.
