### ISSUE TITLE
Да се съберат SSH ключове на NOC

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#33]
- [x] ignisf
- [x] Леков
- [x] maniax
- [x] Тишо
- [x] Щери
- [x] zeridon
- [x] lz1irq
- [x] Точо
- [x] robotpanic

**Comment by lz1irq** [comment]
https://lz1irq.net/tardis.key

**Comment by zeridon** [comment]
Отбелязани според кои ключове са в authorized_keys

**Comment by ignisf** [comment]
@krokodilerian да каже дали миналогодишния му ключ е още актуален

**Comment by tochev** [comment]
@ignisf новия на @krokodilerian , както и моя са сложени на root@eric

**Comment by robotpanic** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBs7aoWTUKwLUzsiHf+RGyS7x+MlSAfq2SIZUP2+Cn+0/Mhyyf5aAWYSXNL+Z7JgbqBRjRdMb6W5iXmEv97rNYzRUFnqCQf8ryw4KuAH6sZiuWxHXES6EPQ2REZrpGtPqzzBy+/6QDvSkPgRvieXVHIXUM+TkLigK4JMcZxYqgIMff/0LptSjicsirCJMRK23qQbUvADvcwBWwq32WfghNJnHS6Kb41tls2lcuxZFylIxfbUbS0+L/uuJtLqy57wu+lUbhKL2JEs13KC60onIG+Gu38jetVQtuFc+NmTu2/+Me3356sxbCsjgRnbWelEOk/pxZdkpXJriwjLoysVRP kalin@linux-4be8.suse

**Comment by zeridon** [comment]
Добавен

**Comment by Arcopix** [comment]
Ключа на Щери:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAhlZuCF1aYdtMeHNrl+aO3d1hS5B2fkf3lWXufHQKuD9liGf1JDHgh8zwIH3jjE+d0d/iy3LV4dfrChjIcfhX+mfC4Nj6YLDmSakE1XnuyTMOv/+PfqZ4Dvb/CT21lfZ/i9P5WoQ6TVZynE6YswwOwRDcZRV1FNqjWqy1cWHrESnNxnzGTXiAZFN5o+7uPO8SfrIFzCMypq4JjpowZyb1KTQmAJgO2iBfJADmteKmyz0CYNQw26ThOSFIItO/4TVqOybjIj4oFZoWtIt+kwLs+TSYRLX645kiceH6WwdOXsuazyXbM9W+Xv2BNMIWmvpxIcKOT0C2mAtqhKbTOrCrZCQXq4XaHVx5rcpGjf3GJqGAphQb50gOZphiO5bTVIQ74K6lk6Oj2zhrHycSqKgxBBQEPxCQUvY8OOcZ3ne8azFbdWyDAZZ+IcJk2QlqgRXTd735fnmVSP9qu/G6YJrPo3+FY0e7BA8HALOkLTr20ontE3b7E78wZ2cfBHPyeitPseHhQ5zsuCi10s7dkd5HMP5UhZONj9wOfZ9YhLkFP1MTSC+UVcKmPpAjNQuu2xoTkoKdxX3DNrFyX2jTdPfIT++gpX7p298ajyxSJNM0kDvkAoxTXT/yNF2MFsSEWEhDRLw94GCNIildiowl7CtG8o9UsE29/Tb8FA2lBMD1Sw== syrinx@demetra

**Comment by Arcopix** [comment]
Всички ключове вече са налице в autorized_keys
