### ISSUE TITLE
Да се прекара POE

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#35]
Да се измисли кои AP-та има смисъл да са с PoE  и да се намерят инжектори и сплитери.

**Comment by lz1irq** [comment]
От доста време се каня да го напиша... в офиса ползваме [TP-Link TLPOE10R](https://www.jarcomputers.com/PoE-Splitter-TP-Link-TL-POE10R_prod_NTLATPLINKTLPOE10R.html) PoE сплитери, които могат да изкарат 5, 9 или 12V DC. На 12V токът е само 1A, но ми се струва, че е достатъчен за Archer-ите (техните адаптери са 2.5A, защото са презапасени за USB дискове).

**Comment by tochev** [comment]
На теория би следвало да стане:
https://wiki.openwrt.org/toh/tp-link/archer-c5-c7-wdr7500#power_consumption
https://blog.dest-unreach.be/2016/01/18/tp-link-archer-c7-power-consumption

Но трябва да се тества с нашия firmware:
- boot
- работа при:
  - пълно cpu натоварване (понеже ще run-ваме разни тестове)
  - пълно натоварване на 3-4 порта
  - натоварване на 5 и 2.4 като им вдигнем мощността колкото може

Хубаво е да изключим и usb портовете, ако може, да не реши някой да си зарежда телефона на тях.

**Comment by ignisf** [comment]
В лаба пристигнаха 6 48-волтови гигабитови PoE инжектора microsemi powerdsine 3501g. Следващата питанка са сплитери.

**Comment by ignisf** [comment]
@krokodilerian, 4 PoE сплитера

**Comment by ignisf** [comment]
done
