### ISSUE TITLE
IRC/Slack/Twitter - канали

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#37]

**Comment by lz1irq** [comment]
Проблем - синхронизацията на Slack с IRC не публикува съобщения от интеграциите (като nagios) в IRC.

**Comment by zeridon** [comment]
Оказва се че бота се прави на интересен и синква само хора.

**Comment by zeridon** [comment]
Освен това се оказва че "attachment" RTM апи-то на слак поддържа доста повече неща освен message.text.

**Comment by zeridon** [comment]
Я да си енкоднем нещата като хората

**Comment by zeridon** [comment]
and it did not work a second time

**Comment by zeridon** [comment]
Replacements kill us :(

**Comment by zeridon** [comment]
Интеграцията в бота е фиксната и поддържа:
- https://github.com/ekmartin/slack-irc
- Github
- ботове които ползват атачмънт апи-то

**Comment by ignisf** [comment]
Докъде сте с това?

**Comment by zeridon** [comment]
- Twitter - ignore медия екипа да се оправя с това
- IRC/Slack - създадени са каналите и са свързани както следва

| SLACK | IRC |
| --- | --- |
| #general | #openfest |
| #noc | #of-noc |
| #video | #video |
| #bulgaria-hall | #openfest-bulgaria |
| #chamber-hall | #openfest-chamber |
| #music-hall | #openfest-music |
- Бота прави логове
