### ISSUE TITLE
Радиостанции + хендсфрита

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#38]
И да се реши къде и кой трябва да има радиостанции, колко можем да вземем и от кого.

**Comment by lz1irq** [comment]
Списък с хората, от които можем да вземем станции:
- [x] 1  от мен - няма хендсфри (поръчал съм си, но надали ще дойде за феста)
- [ ] 5 от познат радиолюбител - имат хендсфрита
- [ ] 2 от Стоил - имат хендсфрита
- [ ] 2 от vloo - имат хендсфрита
- [x] 1 станция от @agit0 - има хендсфри
- [x] 1 станция от @Dragast  - има хендсфри
- [x] 2 станции от @zeridon - имат хендсфри
- [x] 1 от Пешо
- [ ] 6 от Мариан - 5 Quansheng, 1 Baofeng
- [x] 2 от @ignisf

Общо: 16

**Comment by lz1irq** [comment]
@zeridon Любо1 e @Agit0

**Comment by zeridon** [comment]
Вече имаме и кабел за програмиране

**Comment by ignisf** [comment]
@isld ^

**Comment by isld** [comment]
Аз имам една и ще си я ползвам. Миналата година бях взел две от едни колеги, но предвид мазалото със зарядни, хендс-фриита, кутии и т.н., тая година не се наемам да взимам чужди.

**Comment by ignisf** [comment]
+2 от мен

**Comment by zeridon** [comment]
Време е да почнем да ги събираме. При първа възможност ще оставя моите.

@lz1irq може ли да приготвиш chirp конфиг който да става за наливане. Каналите да са надписани по цели може би ще е най-добре. На място по време на сетъпа ще решим на канали и после може да заключим радията за да няма бърникания. Или да ги префлашнем с новия конфиг.

**Comment by ignisf** [comment]
Done
