### ISSUE TITLE
Шейпинг, който да гарантира bandwidth за стриймовете

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#4]
От миналата година https://github.com/OpenFest/openfest-2015-network/issues/42

**Comment by ignisf** [comment]
https://wiki.openwrt.org/doc/howto/packet.scheduler/packet.scheduler.example4 ?

**Comment by krokodilerian** [comment]
Не знам дали политически искаме да shape-ваме и дали ще постигнем нещо по-добро. Ще ни помогне в момента, в който някой точи torrent-и, иначе като цяло прави по-трудно да си напълним канала :)

**Comment by zeridon** [comment]
В случая не виждам какво толкова политическо има. Необходим е гарантиран канал за да излезнат стриймовете навънка (2-4 стрийма по 1-3 мбита). Останалото да си е free-for-all. Евентуално приоритизация на дребен трафик (dns, icmp).

**Comment by krokodilerian** [comment]
Ами ние изходящ трафик почти нямаме, изобщо не се притеснявам за stream-овете.

**Comment by ignisf** [comment]
Почти не сме имали _досега_, you never know кога някой ще се шибне в някой суич и ще почне да прави мизерии. Докато го намерим стриймове ще няма =).

Освен това стриймовете ти са по TCP и ACK-овете от сървъра е редно да могат да стигат (и то навреме) дори някой да тегли яко.

Иначе замислите са два – едновременно да са приоритизирани „потоците“ на стриймовете над всичко останало (или да им се гарантира BW) И да се приложи scheduling политика, която да позволява използването на нета дори при запълнен ъплинк. Разпределянето на bandwidth-а поравно е вредно и не ни трябва. Трябва ни нещо да се грижи лейтънсито да е ниско за всички, ако се случи някой да е напълнил ъплинка. Мисля, че FQ CODEL се грижи за това. Further research needed.

**Comment by ignisf** [comment]
И допълнително можем да проиграем сценарии да проверим какво ще се случи без шейпинг и ако има нужда, да го правим.

**Comment by krokodilerian** [comment]
Ами... явно ще разпъваме вече setup-а в лаба. Иначе, моите сблъсъци с linux-ките shaper-и не са от най-приятните и още нямам голяма вяра в тях, но определено може да симулираме.

**Comment by ignisf** [comment]
Затваряме засега

**Comment by ignisf** [comment]
Отварям наново, защото според мен е редно поне да проучим ефекта от сетване на mq (tc-mqprio(8)) на eth0 и eth1 и fq_codel (tc-fq_codel(8)) по подразбиране. Мрежовите карти на eric поддържат multiqueue.

**Comment by krokodilerian** [comment]
В момента се тества в лаба и ефектът е учудващо добър. Може да взема да си променя мнението :)

**Comment by ignisf** [comment]
Така и не стигнахме до това
