### ISSUE TITLE
Инвентаризация на кабелите (лан)

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#46]

**Comment by lz1irq** [comment]
При първа възможност ще донеса pockethernet и Mastech-ския тестер в лаба, за да премерим мрежовите кабели по-лесно и бързо.

**Comment by ignisf** [comment]
@lz1irq това готово ли е?

**Comment by lz1irq** [comment]
Ако не броим "кабелите зад гърба на Владо", е готово. Този уикенд, ако най-накрая съм по-добре, може да мина през лаба да измеря и надпиша и тях.
