### ISSUE TITLE
Система за обратна връзка за качеството на безжичната мрежа

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#51]
бланки за фийдбек и кутия

**Comment by zeridon** [comment]
А нещо онлайн? И евентуално може би да казва ако репорта е "достатъчно" лош?

**Comment by ignisf** [comment]
Идеята да е офлайн е да можеш да репортнеш, ако нямаш нет

**Comment by zeridon** [comment]
Ммм тогава някой ще трябва да ги обикаля тея кутии доста често. По скоро да докладва на рецепция и от там по радиото.

**Comment by zeridon** [comment]
Може ли да смятаме билета за приключен или да си планираме 4-5 кутии пръснати насам за впечатления.

**Comment by ignisf** [comment]
Ще помисля още малко, мисля да имплементирам система за обратна връзка за целия фест и за отделните лекции, така че нека си стои отворено засега :)
