### ISSUE TITLE
Да се прослуша ефира за PMR честоти и да се подбере свободна

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#52]
За да не сме в пререкания с КРС ще наложи радиостанциите да работят в PMR честотите (аналоговите).

Да се закачи един SDR няколко дни по рано и да се прослуша лентата.

REF: https://en.wikipedia.org/wiki/PMR446#Analogue_FM

**Comment by zeridon** [comment]
Свързано с #38

**Comment by lz1irq** [comment]
Няма смисъл много предварително да се прослушва, тъй като трафикът на тези честоти е доста променлив (ремонти, строежи и т.н.). Но миналата година нямаше проблеми с интерференция от други станции, не очаквам и тази да има.

**Comment by ignisf** [comment]
Нека да си го отметнем по време на сетъпа това.

**Comment by ignisf** [comment]
Done?
