### ISSUE TITLE
Услуги на eric, чиято конфигурация е нужно да се провери

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#54]
- [ ] snmpd
- [x] snmptrapd
- [x] snmptt
- [x] collectd
- [x] carbon-cache@a
- [x] carbon-aggregator@top
- [ ] minissdpd?
- [ ] munin-node
- [x] uwsgi
- [x] php-fpm
- [x] nginx
- [ ] apache2
- [x] arpwatch
- [x] grafana-server

Спрял съм ги наръка преди да ни трябват

**Comment by zeridon** [comment]
| Service | Needed | Configured | Enable | Comment |
| --- | --- | --- | --- | --- |
| snmp | no | no | no |  |
| snmptrapd | yes | yes | yes | trap receiver |
| snmptt | yes | yes | no | trap translator |
| collectd | yes | yes | yes | graph datapoints ingestor |
| carbon-cache@a | yes | yes | yes | graph points storage |
| carbon-aggregator@top | yes | yes | yes | graph points aggregation/mangle |
| minissdpd? | no | no | removed |  |
| munin-node | yes? | yes | no? | мониторинг от @krokodilerian ? |
| uwsgi | yes | yes | yes | graphite-web |
| php-fpm | yes? | yes | yes? | nagios landing. Ако го дъмпим на хтмл може и без него май |
| nginx | yes | yes | yes | web |
| apache2 | no | yes | removed | nagios proxy - removed |
| arpwatch | yes | yes | yes | visitor tracking |
| grafana-server | yes | yes | yes | dashboards #64 |
| nodejs | yes? | no | yes? | lightning talks timer |

**Comment by ignisf** [comment]
@zeridon nodejs не ти ли е нужен за графана?

**Comment by zeridon** [comment]
Тя е писана на GO и е единична бинарка

**Comment by ignisf** [comment]
huh... cool
