### ISSUE TITLE
systemd-systemctl фейлва при стартиране

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#56]
```
Aug 31 02:06:13 eric systemd-sysctl[3026]: Failed to write '1# Increase the maximum amount of option memory buffers' to '/proc/sys/net/ipv4/tcp_window_scaling': Invalid argument
Aug 31 02:06:13 eric systemd[1]: systemd-sysctl.service: main process exited, code=exited, status=1/FAILURE
Aug 31 02:06:13 eric systemd[1]: Failed to start Apply Kernel Variables.
```

**Comment by zeridon** [comment]
Изглежда като кофти paste

Сваляне на коментара на нов ред изглежда оправя проблема.

Евентуално ребуут и проверка ще го верифицират.

**Comment by ignisf** [comment]
Давай

**Comment by zeridon** [comment]
`# systemctl status systemd-sysctl.service 
● systemd-sysctl.service - Apply Kernel Variables
   Loaded: loaded (/lib/systemd/system/systemd-sysctl.service; static)
   Active: active (exited) since Wed 2016-08-31 10:58:07 EEST; 7min ago`
