### ISSUE TITLE
Да се изключи ASR/watchdog

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#57]
"ASR-а си върви и щом си върви ще се включи" -- народна поговорка от среднощни главоболия :)

**Comment by ignisf** [comment]
Мисля, че е зададен action: none на watchdog timeout

**Comment by zeridon** [comment]
Имам по скоро в предвид ASR функционалността в iLO-то.

Поне на G5 сериите преди години ако беше пуснат поне веднъж на 2-3 месеца илото решаваше че става нещо и застрелваше машината.

**Comment by ignisf** [comment]
Това май го направих, но трябва да го doublecheck-неш, @zeridon

**Comment by zeridon** [comment]
```
# hpasmcli -s "show asr"

ASR timeout is 10 minutes.
ASR is currently disabled.
```
