### ISSUE TITLE
Оптиката е преместена, да се провери къде и да се прекара мед от там до сървърното

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#61]
- [x] Да се уговорим за оглед с netx
- [x] Да прекараме кабел до сървърното
- [x] Да се смени медия конвертор

**Comment by ignisf** [comment]
Днес ми се обадиха от NETX и направо се разбрахме веднага да отидем да огледаме, те ще минат в понеделник в 17:00 да си прекарат кабел. Няма да имам нужда от помощ.

**Comment by ignisf** [comment]
Днес се разминахме с филхармонията и нетх, остава за утре

**Comment by ignisf** [comment]
Прекаран е кабел от офиса на втория етаж до зад органа. Седи навит на перваза на офиса. Когато дойде време за феста, ще го пуснем през прозореца. За съжаление не можахме да го прекараме покрай другите кабели с хората от netx, а не е редно да дупчим фасадата или дограмата.

**Comment by krokodilerian** [comment]
Говорихте ли с хората там доколко е ок да стои отворен прозореца за два-три дни?

**Comment by ignisf** [comment]
Да. Човекът каза, че е ОК, отваря се отгоре, а и без това те го държат отворен, защото са 5-6 души на 20 квадрата

**Comment by zeridon** [comment]
- [ ] gaffer tape за да се закрепи кабела
- [ ] блокче за да се блокира прозореца в отворено състояние
