### ISSUE TITLE
Да се финализира топологията на мрежата

### ISSUE THREAD

**Issue by krokodilerian** [OpenFest/openfest-network-2016#66]
https://github.com/OpenFest/openfest/blob/master/2016/schemes/network.pdf

Това е с всичко, което се сещам. Забележки, промени и т.н.?

Разликите от миналата година са:
nocsw е преименуван на vocsw
има друг nocsw в мазето
има още едно AP в мазето
има userswitch в студио музика
има intercom за камерите (съответно малко повече vlan-и на няколко AP-та)

**Comment by zeridon** [comment]
Струва ми се няма друго така че е за затваряне направо

**Comment by zeridon** [comment]
Любо спомена че има 3 интеркома в българия а на схемата виждам само 2.

**Comment by krokodilerian** [comment]
Има два слушателя и един предавател (където е пулта). Слуша се на главната камера и на тая за публиката, общия план не би трябвало да има intercom.
