### ISSUE TITLE
Подготовка на ерик за събитието

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2016#67]
Ерик да бъде почистен преди събитието
- [x] snmptrapd - enable & start
- [x] nagios - enable & start
- [x] collectd - enable & start
- [x] carbon-cache@a - clean /opt/graphite/storage/_/_ leave db and index, enable & start
- [x] carbon-aggregator@top - enable & start
- [x] arpwatch - clean logs, /var/lib, enable & start
- [x] uwsgi - enable & start
- [x] nginx - enable & start
- [x] php-fpm - enable & start
- [x] fcgiwrapd - enable & start
- [x] grafana-server - enable & start, set default dashboard for Guests
- [x] rsyslog - clean /opt/syslog, restart
- [x] nagios - enable notifications, enable & start

**Comment by robotpanic** [comment]
root@eric:/etc # wall
Ima li oshte neshto za konfene?
kiliev

Broadcast message from root@eric (pts/2) (Tue Oct 25 12:31:02 2016):  

Тъй като гледам са запалени services : 

root@eric:/var/tmp # for service in `cat servicechecker.sh | cut -d \- -f 1` ; do systemctl | grep ${service} ; done
nagios3.service                                                                                         loaded active running   LSB: nagios host/service/network monitoring and management system
collectd.service                                                                                        loaded active running   Statistics collection and monitoring daemon
carbon-aggregator@top.service                                                                           loaded active running   carbon-aggregator instance top (graphite)
carbon-cache@a.service                                                                                  loaded active running   carbon-cache instance a (graphite)
system-carbon\x2daggregator.slice                                                                       loaded active active    system-carbon\x2daggregator.slice
system-carbon\x2dcache.slice                                                                            loaded active active    system-carbon\x2dcache.slice
carbon-aggregator@top.service                                                                           loaded active running   carbon-aggregator instance top (graphite)
carbon-cache@a.service                                                                                  loaded active running   carbon-cache instance a (graphite)
system-carbon\x2daggregator.slice                                                                       loaded active active    system-carbon\x2daggregator.slice
system-carbon\x2dcache.slice                                                                            loaded active active    system-carbon\x2dcache.slice
uwsgi.service                                                                                           loaded active running   LSB: Start/stop uWSGI server instance(s)
nginx.service                                                                                           loaded active running   LSB: starts the nginx web server
php5-fpm.service                                                                                        loaded active running   The PHP FastCGI Process Manager
grafana-server.service                                                                                  loaded active running   Starts and stops a single grafana instance on this system
rsyslog.service                                                                                         loaded active running   System Logging Service
nagios3.service                                                                                         loaded active running   LSB: nagios host/service/network monitoring and management system
root@eric:/var/tmp #

**Comment by zeridon** [comment]
@robotpanic този тикет си е за самия ден за последна проверка и почистване. Ще се прави в петък.

**Comment by robotpanic** [comment]
Сложих фейлтубан, че китайците полазиха  

[1]+  Stopped                 less /var/log/auth.log
root@eric:/etc/fail2ban # !vim
vim jail.local 
root@eric:/etc/fail2ban # /etc/init.d/fail2ban restart
[ ok ] Restarting fail2ban (via systemctl): fail2ban.service.
root@eric:/etc/fail2ban # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination  
fail2ban-ssh  tcp  --  anywhere             anywhere             tcp dpt:ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain fail2ban-ssh (1 references)
target     prot opt source               destination  
REJECT     all  --  116.31.116.14        anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere  
root@eric:/etc/fail2ban #
