### ISSUE TITLE
WRT1900ACS-ите поддържат само VLAN ID-та от 0 до 63

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#68]

**Comment by zeridon** [comment]
Така както го виждам имаме 3 опции:
- Зарязваме ги (но са 4 броя)
- Сменяме VLAN-ите да са на база 30
  - mgmt 20
  - wired 21
  - wireless 22
  - video 23
  - overflow 24
- Сменяме VLAN-а за wireless и правим VLAN bridging (което си нямам идея но @ignisf го спомена)

Последната опция нещо мен лично не ме радва (нито втората). Ако настояваме да ги ползваме (за придобиване на опит) може да може да опитаме втората, но като цял такъв хардуер не ме радва. В тея години трябва да си доста ръб за да не можеш да си позволиш битовете за за обработка на VLAN таговете в трафика.

**Comment by ignisf** [comment]
cc @hackman 😂

**Comment by ignisf** [comment]
спестили са цели 6 бита между другото ;). На archer-ите май бяха до 127, т.е. 7-битово поле или с един бит по-голямо от линксисите.

**Comment by krokodilerian** [comment]
Това има ли го документирано някъде? Да не би да има само 63 vlan-а без значение кой им е номера или настройка или нещо такова, виждал съм всякакви странности по мрежово оборудване?

Като гледам, имаме точно 4 spare, като две не са особено добри. Единствената опция е да сменим vlan-ите, което по принцип не е особено сложно, просто е играчка.

**Comment by ignisf** [comment]
не можах да го намеря в документацията, но да, за id-та говорим 😔

**Comment by krokodilerian** [comment]
Сменям vlan-ите, #69.
