### ISSUE TITLE
Смяна на vlan-ите

### ISSUE THREAD

**Issue by krokodilerian** [OpenFest/openfest-network-2016#69]
Заради #68 трябва да сменим vlan-ите. Новата конфигурация ще е:

id      range                   name
10      46.233.38.137/28        external
20      10.20.0.0/24            mgmt
21      10.21.0.0/22            wired
22      10.22.0.0/22            wireless
23      10.23.0.0/24            video
24      10.24.0.0/24            overflow

ipv6

10 2a01:b760:1::/127
21 2a01:b760:abc:2::/64
22 2a01:b760:abc:3::/64

Има да се пренастроят:
- [x] switch-овете на лаба (rack-sw, wr-switch)
- [x] coresw
- [x] eric/interfaces
- [x] eric/nagios
- [x] eric/dhcp

и после останалите неща.

**Comment by krokodilerian** [comment]
Даже не си отрязах клона.

**Comment by zeridon** [comment]
Защо да сменяме адресите? Бяха си добре и така.

**Comment by krokodilerian** [comment]
щото така отговарят на номера на vlan-а и е доста по-лесно.
