### ISSUE TITLE
Разпространяване на изображения с пачовете ни за OpenWrt за тестване

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#7]

**Comment by ignisf** [comment]
Затварям, тестовите имиджи в офиса на крок и lz1irq се държат относително добре, с изключение на бъг, заради който се натрупват пакети и се изсипват след това наведнъж.

**Comment by krokodilerian** [comment]
Аз лично не се радвам на поведението, но при нас има psk и enterprise и има места в офиса, на които roaming-а просто ебава майката на всичко. Знам конкретното място и искам да изтествам с @lz1irq , като се излекува да видим къде е проблема.

**Comment by ignisf** [comment]
Ето [ишу за това](https://github.com/OpenFest/openfest-network/issues/63), това го затварям – който е искал да си сложи такива имиджи, го е направил.
