### ISSUE TITLE
Call for hardware

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network-2016#8]
- [x] Да се опише какъв хардуер търсим
- [x] Да се обяви на съответните места
- [x] Да се направи система за инвентаризация

**Comment by ignisf** [comment]
Търсен хардуер:
- 8 бекбоун суича
- 4 юзърски суича
- 1 NOC switch
- 3 legacy AP-та
- 12 dualband AP-та
- 2x рутера
- два монитора + лаптоп за NOC-а
- 4x PoE kits

Наличен:
- Суичове:
  - Лаб: 3х tp-link sg3210
    - catalyst express 500g 12x1Gbit
    - catalyst 3550 10+2 1Gbit
    - catalyst 4848 48x1g +2x10g
    - някой суич за новия NOC leaf
    - някои суичове за user-ски leaf-ове
  - Леков: catalyst 3750g 24x1g
  - Светла: catalyst 3750g 24x1g
        \* catalyst 4848 48x1g +2x10g (Стамов)
  - Securax: 2x hp 1824g (leaf)
  - Digger: 2x микротик
- AP-та
  - Петко: 1 legacy tp-link 841ND
    - 1 tp-link archer c5
  - Леков: archer c5
    - wdr 4300
  - Точо: archer c5
    - wdr 4300
  - Васил: archer c5
  - Securax: archer c7
  - Лаб: wdr4300
    - dap2695
    - archer c5
  - Мариян: ?
  - neter: archer c7
  - Тишо: wr1043

**Comment by krokodilerian** [comment]
Update:
Изгоря ни catalyst 3550;
Дойдоха още 3  tp-link sg3210;

**Comment by ignisf** [comment]
и имаме още един DAP-2695, заедно с двата WRT1900ACS от @hackman, ни излиза сметката

**Comment by krokodilerian** [comment]
Още два или още един?

**Comment by ignisf** [comment]
един DAP и два WRT1900

**Comment by hackman** [comment]
Общо имаме 4 WRT1900ACS. Просто не всичките са в лаба :)

**Comment by eniac111** [comment]
Мога да осигуря 1-2 лаптопа + 1 x 26" монитор и два китайски по 17"?

**Comment by krokodilerian** [comment]
@eniac111 , ще ги приемем :)

**Comment by ignisf** [comment]
нали не са CRT? :)

**Comment by eniac111** [comment]
не, но са доста скапани. Софтуерът им забива понякога

**Comment by Arcopix** [comment]
Говорих с Digger-а:
- потвърждава двата микротика
- има catalyst 2950 (10/100) с още два гигабитови порта

**Comment by krokodilerian** [comment]
10/100 switch-ове с 2 gbps порта имаме една кофа в лаба не са проблем. microtic-овете ще са полезни, че са тихи и гигабитови.

**Comment by krokodilerian** [comment]
@eniac111 , какво точно им забива? Някакси не е хубаво да следим мрежата от устройства, дето половината време не работят. Ние ще ги ползваме в общи линии да показват на цял екран малко видеа и някой друг browser, с това ще се справят ли

**Comment by eniac111** [comment]
@krokodilerian Забива им само менюто, не е фатално. Не са по- добри от тези в лаба

**Comment by krokodilerian** [comment]
@eniac111, ок, ще ги вземем. Къде са и кога могат да се вземат?

**Comment by eniac111** [comment]
@krokodilerian трябва само да си инсталирам новия сървър и ще ги занеса в лаба.

**Comment by ignisf** [comment]
Още две радиостанции от мен

**Comment by krokodilerian** [comment]
Светла е донесла switch-а в лаба.

**Comment by hackman** [comment]
Аз мога да осигуря и 6 професионални радио станции

**Comment by zeridon** [comment]
@hackman какво ще рече професионални? Модел?

**Comment by ignisf** [comment]
Done
